CREATE DATABASE students;

USE students;

create table student(
   student_id INT NOT NULL,
   name VARCHAR(25) NOT NULL,
   sex VARCHAR(25) NOT NULL,
   age INT NOT NULL,
   PRIMARY KEY ( student_id )
);

insert into student (student_id, name, sex, age) values (1, "Alice", "Female", 20);
insert into student (student_id, name, sex, age) values (2, "Bob", "Male", 21);
insert into student (student_id, name, sex, age) values (3, "Peter", "Male", 22);
insert into student (student_id, name, sex, age) values (4, "George", "Male", 27);
insert into student (student_id, name, sex, age) values (5, "William", "Male", 28);
insert into student (student_id, name, sex, age) values (6, 'Boony', 'Male', 64);
insert into student (student_id, name, sex, age) values (7, 'Trev', 'Male', 22);
insert into student (student_id, name, sex, age) values (8, 'Feodor', 'Male', 77);
insert into student (student_id, name, sex, age) values (9, 'Oneida', 'Female', 66);
insert into student (student_id, name, sex, age) values (10, 'Bernardina', 'Female', 97);
insert into student (student_id, name, sex, age) values (11, 'Sofia', 'Female', 32);
insert into student (student_id, name, sex, age) values (12, 'Ugo', 'Male', 21);
insert into student (student_id, name, sex, age) values (13, 'Dorotea', 'Female', 53);
insert into student (student_id, name, sex, age) values (14, 'Agosto', 'Male', 77);
insert into student (student_id, name, sex, age) values (15, 'Brant', 'Male', 80);
insert into student (student_id, name, sex, age) values (16, 'Benoit', 'Male', 72);
insert into student (student_id, name, sex, age) values (17, 'Benjie', 'Male', 52);
insert into student (student_id, name, sex, age) values (18, 'Eliot', 'Male', 73);
insert into student (student_id, name, sex, age) values (19, 'Biron', 'Male', 93);
insert into student (student_id, name, sex, age) values (20, 'Finlay', 'Male', 28);
insert into student (student_id, name, sex, age) values (21, 'Valentin', 'Male', 86);
insert into student (student_id, name, sex, age) values (22, 'Kendell', 'Male', 22);
insert into student (student_id, name, sex, age) values (23, 'Cherilyn', 'Female', 39);
insert into student (student_id, name, sex, age) values (24, 'Alric', 'Male', 85);
insert into student (student_id, name, sex, age) values (25, 'Farand', 'Female', 46);
insert into student (student_id, name, sex, age) values (26, 'Corbet', 'Male', 24);
insert into student (student_id, name, sex, age) values (27, 'Torr', 'Male', 66);
insert into student (student_id, name, sex, age) values (28, 'Leontyne', 'Female', 38);
insert into student (student_id, name, sex, age) values (29, 'Dannie', 'Male', 51);
insert into student (student_id, name, sex, age) values (30, 'Ulrica', 'Female', 26);
insert into student (student_id, name, sex, age) values (31, 'Boycie', 'Male', 74);
insert into student (student_id, name, sex, age) values (32, 'Peggy', 'Female', 59);
insert into student (student_id, name, sex, age) values (33, 'Herbie', 'Male', 91);
insert into student (student_id, name, sex, age) values (34, 'Dunn', 'Male', 83);
insert into student (student_id, name, sex, age) values (35, 'Arleta', 'Female', 50);
insert into student (student_id, name, sex, age) values (36, 'Inge', 'Female', 77);
insert into student (student_id, name, sex, age) values (37, 'Alley', 'Male', 58);
insert into student (student_id, name, sex, age) values (38, 'Petey', 'Male', 45);
insert into student (student_id, name, sex, age) values (39, 'Perice', 'Male', 80);
insert into student (student_id, name, sex, age) values (40, 'Irwinn', 'Male', 27);
insert into student (student_id, name, sex, age) values (41, 'Harold', 'Male', 64);
insert into student (student_id, name, sex, age) values (42, 'Bryna', 'Female', 74);
insert into student (student_id, name, sex, age) values (43, 'Riley', 'Male', 20);
insert into student (student_id, name, sex, age) values (44, 'Emile', 'Male', 46);
insert into student (student_id, name, sex, age) values (45, 'Gran', 'Male', 61);
insert into student (student_id, name, sex, age) values (46, 'Renato', 'Male', 42);
insert into student (student_id, name, sex, age) values (47, 'Anjanette', 'Female', 22);
insert into student (student_id, name, sex, age) values (48, 'Hal', 'Male', 93);
insert into student (student_id, name, sex, age) values (49, 'Dora', 'Female', 75);
insert into student (student_id, name, sex, age) values (50, 'Silvester', 'Male', 84);
insert into student (student_id, name, sex, age) values (51, 'Gianina', 'Female', 65);
insert into student (student_id, name, sex, age) values (52, 'Letitia', 'Female', 92);
insert into student (student_id, name, sex, age) values (53, 'Dex', 'Male', 31);
insert into student (student_id, name, sex, age) values (54, 'Kaleb', 'Male', 77);
insert into student (student_id, name, sex, age) values (55, 'Courtnay', 'Male', 84);
insert into student (student_id, name, sex, age) values (56, 'Philippe', 'Female', 53);
insert into student (student_id, name, sex, age) values (57, 'Maurizia', 'Female', 87);
insert into student (student_id, name, sex, age) values (58, 'Billie', 'Female', 34);
insert into student (student_id, name, sex, age) values (59, 'Lisha', 'Female', 87);
insert into student (student_id, name, sex, age) values (60, 'Leona', 'Female', 22);
insert into student (student_id, name, sex, age) values (61, 'Vicky', 'Female', 62);
insert into student (student_id, name, sex, age) values (62, 'Kerby', 'Male', 25);
insert into student (student_id, name, sex, age) values (63, 'Meghan', 'Female', 55);
insert into student (student_id, name, sex, age) values (64, 'Rainer', 'Male', 99);
insert into student (student_id, name, sex, age) values (65, 'Tedi', 'Female', 63);
insert into student (student_id, name, sex, age) values (66, 'Carly', 'Female', 75);
insert into student (student_id, name, sex, age) values (67, 'Debi', 'Female', 25);
insert into student (student_id, name, sex, age) values (68, 'Tanya', 'Female', 63);
insert into student (student_id, name, sex, age) values (69, 'Emyle', 'Female', 51);
insert into student (student_id, name, sex, age) values (70, 'Nicolas', 'Male', 81);
insert into student (student_id, name, sex, age) values (71, 'Kass', 'Female', 30);
insert into student (student_id, name, sex, age) values (72, 'Hart', 'Male', 94);
insert into student (student_id, name, sex, age) values (73, 'Ninette', 'Female', 64);
insert into student (student_id, name, sex, age) values (74, 'Ware', 'Male', 74);
insert into student (student_id, name, sex, age) values (75, 'Molli', 'Female', 63);
insert into student (student_id, name, sex, age) values (76, 'Dorena', 'Female', 88);
insert into student (student_id, name, sex, age) values (77, 'Heath', 'Male', 54);
insert into student (student_id, name, sex, age) values (78, 'Elvera', 'Female', 96);
insert into student (student_id, name, sex, age) values (79, 'Nelie', 'Female', 69);
insert into student (student_id, name, sex, age) values (80, 'Odey', 'Male', 19);
insert into student (student_id, name, sex, age) values (81, 'Brande', 'Female', 66);
insert into student (student_id, name, sex, age) values (82, 'Laurice', 'Female', 74);
insert into student (student_id, name, sex, age) values (83, 'Liuka', 'Female', 47);
insert into student (student_id, name, sex, age) values (84, 'Tamara', 'Female', 85);
insert into student (student_id, name, sex, age) values (85, 'Hewet', 'Male', 19);
insert into student (student_id, name, sex, age) values (86, 'Nanci', 'Female', 90);
insert into student (student_id, name, sex, age) values (87, 'Blondie', 'Female', 59);
insert into student (student_id, name, sex, age) values (88, 'Eugenius', 'Male', 70);
insert into student (student_id, name, sex, age) values (89, 'Corby', 'Male', 52);
insert into student (student_id, name, sex, age) values (90, 'Ludwig', 'Male', 96);
insert into student (student_id, name, sex, age) values (91, 'Buiron', 'Male', 59);
insert into student (student_id, name, sex, age) values (92, 'Rorke', 'Male', 46);
insert into student (student_id, name, sex, age) values (93, 'Shannon', 'Male', 53);
insert into student (student_id, name, sex, age) values (94, 'Karin', 'Female', 42);
insert into student (student_id, name, sex, age) values (95, 'Bette', 'Female', 59);
insert into student (student_id, name, sex, age) values (96, 'Octavius', 'Male', 89);
insert into student (student_id, name, sex, age) values (97, 'Alfons', 'Male', 29);
insert into student (student_id, name, sex, age) values (98, 'Rog', 'Male', 86);
insert into student (student_id, name, sex, age) values (99, 'Gus', 'Male', 46);
insert into student (student_id, name, sex, age) values (100, 'Durant', 'Male', 83);
